[package]
name = "vram-retest-client"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
wayland-client = "=0.31.15"
wayland-protocols = { version = "=0.32.13", features = ["client", "staging", "unstable"] }
serde_json = "1"
tempfile = "3"
libc = "0.2"
x11rb = "=0.13.2"
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols", rev = "32283d7", default-features = false, features = ["client"] }
