[package]
name = "vram-retest-gpu-client"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
gbm = { version = "=0.18.0", default-features = false }
libc = "0.2"
serde_json = "1"
wayland-client = "=0.31.15"
wayland-protocols = { version = "=0.32.13", features = ["client"] }

[dev-dependencies]
tempfile = "3"
